/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CommitDetail;
import org.openapitools.client.model.PreviousBuild;
import org.openapitools.client.model.User;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BuildDetail
 */
public class BuildDetailTest {
    private final BuildDetail model = new BuildDetail();

    /**
     * Model tests for BuildDetail
     */
    @Test
    public void testBuildDetail() {
        // TODO: test BuildDetail
    }

    /**
     * Test the property 'allCommitDetails'
     */
    @Test
    public void allCommitDetailsTest() {
        // TODO: test allCommitDetails
    }

    /**
     * Test the property 'compare'
     */
    @Test
    public void compareTest() {
        // TODO: test compare
    }

    /**
     * Test the property 'jobName'
     */
    @Test
    public void jobNameTest() {
        // TODO: test jobName
    }

    /**
     * Test the property 'node'
     */
    @Test
    public void nodeTest() {
        // TODO: test node
    }

    /**
     * Test the property 'previousSuccessfulBuild'
     */
    @Test
    public void previousSuccessfulBuildTest() {
        // TODO: test previousSuccessfulBuild
    }

    /**
     * Test the property 'retries'
     */
    @Test
    public void retriesTest() {
        // TODO: test retries
    }

    /**
     * Test the property 'sshEnabled'
     */
    @Test
    public void sshEnabledTest() {
        // TODO: test sshEnabled
    }

    /**
     * Test the property 'timedout'
     */
    @Test
    public void timedoutTest() {
        // TODO: test timedout
    }

    /**
     * Test the property 'usageQueuedAt'
     */
    @Test
    public void usageQueuedAtTest() {
        // TODO: test usageQueuedAt
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
