/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.Outcome;
import org.openapitools.client.model.Status;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BuildSummary
 */
public class BuildSummaryTest {
    private final BuildSummary model = new BuildSummary();

    /**
     * Model tests for BuildSummary
     */
    @Test
    public void testBuildSummary() {
        // TODO: test BuildSummary
    }

    /**
     * Test the property 'addedAt'
     */
    @Test
    public void addedAtTest() {
        // TODO: test addedAt
    }

    /**
     * Test the property 'buildNum'
     */
    @Test
    public void buildNumTest() {
        // TODO: test buildNum
    }

    /**
     * Test the property 'outcome'
     */
    @Test
    public void outcomeTest() {
        // TODO: test outcome
    }

    /**
     * Test the property 'pushedAt'
     */
    @Test
    public void pushedAtTest() {
        // TODO: test pushedAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'vcsRevision'
     */
    @Test
    public void vcsRevisionTest() {
        // TODO: test vcsRevision
    }

}
