/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CommitDetail
 */
public class CommitDetailTest {
    private final CommitDetail model = new CommitDetail();

    /**
     * Model tests for CommitDetail
     */
    @Test
    public void testCommitDetail() {
        // TODO: test CommitDetail
    }

    /**
     * Test the property 'authorDate'
     */
    @Test
    public void authorDateTest() {
        // TODO: test authorDate
    }

    /**
     * Test the property 'authorEmail'
     */
    @Test
    public void authorEmailTest() {
        // TODO: test authorEmail
    }

    /**
     * Test the property 'authorLogin'
     */
    @Test
    public void authorLoginTest() {
        // TODO: test authorLogin
    }

    /**
     * Test the property 'authorName'
     */
    @Test
    public void authorNameTest() {
        // TODO: test authorName
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'commit'
     */
    @Test
    public void commitTest() {
        // TODO: test commit
    }

    /**
     * Test the property 'commitUrl'
     */
    @Test
    public void commitUrlTest() {
        // TODO: test commitUrl
    }

    /**
     * Test the property 'committerDate'
     */
    @Test
    public void committerDateTest() {
        // TODO: test committerDate
    }

    /**
     * Test the property 'committerEmail'
     */
    @Test
    public void committerEmailTest() {
        // TODO: test committerEmail
    }

    /**
     * Test the property 'committerLogin'
     */
    @Test
    public void committerLoginTest() {
        // TODO: test committerLogin
    }

    /**
     * Test the property 'committerName'
     */
    @Test
    public void committerNameTest() {
        // TODO: test committerName
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

}
