/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectFeatureFlags
 */
public class ProjectFeatureFlagsTest {
    private final ProjectFeatureFlags model = new ProjectFeatureFlags();

    /**
     * Model tests for ProjectFeatureFlags
     */
    @Test
    public void testProjectFeatureFlags() {
        // TODO: test ProjectFeatureFlags
    }

    /**
     * Test the property 'buildForkPrs'
     */
    @Test
    public void buildForkPrsTest() {
        // TODO: test buildForkPrs
    }

    /**
     * Test the property 'fleet'
     */
    @Test
    public void fleetTest() {
        // TODO: test fleet
    }

    /**
     * Test the property 'junit'
     */
    @Test
    public void junitTest() {
        // TODO: test junit
    }

    /**
     * Test the property 'oss'
     */
    @Test
    public void ossTest() {
        // TODO: test oss
    }

    /**
     * Test the property 'osx'
     */
    @Test
    public void osxTest() {
        // TODO: test osx
    }

    /**
     * Test the property 'setGithubStatus'
     */
    @Test
    public void setGithubStatusTest() {
        // TODO: test setGithubStatus
    }

    /**
     * Test the property 'trustyBeta'
     */
    @Test
    public void trustyBetaTest() {
        // TODO: test trustyBeta
    }

}
