/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectUsernameProjectSshKeyPostDefaultResponse
 */
public class ProjectUsernameProjectSshKeyPostDefaultResponseTest {
    private final ProjectUsernameProjectSshKeyPostDefaultResponse model = new ProjectUsernameProjectSshKeyPostDefaultResponse();

    /**
     * Model tests for ProjectUsernameProjectSshKeyPostDefaultResponse
     */
    @Test
    public void testProjectUsernameProjectSshKeyPostDefaultResponse() {
        // TODO: test ProjectUsernameProjectSshKeyPostDefaultResponse
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
