/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Lifecycle
 */
@JsonAdapter(Lifecycle.Adapter.class)
public enum Lifecycle {
  
  QUEUED("queued"),
  
  SCHEDULED("scheduled"),
  
  NOT_RUN("not_run"),
  
  NOT_RUNNING("not_running"),
  
  RUNNING("running"),
  
  FINISHED("finished");

  private String value;

  Lifecycle(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Lifecycle fromValue(String value) {
    for (Lifecycle b : Lifecycle.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Lifecycle> {
    @Override
    public void write(final JsonWriter jsonWriter, final Lifecycle enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Lifecycle read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Lifecycle.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Lifecycle.fromValue(value);
  }
}

