/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Status;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * previous build
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T12:24:12.418068+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class PreviousBuild {
  public static final String SERIALIZED_NAME_BUILD_NUM = "build_num";
  @SerializedName(SERIALIZED_NAME_BUILD_NUM)
  @javax.annotation.Nullable
  private Integer buildNum;

  public static final String SERIALIZED_NAME_BUILD_TIME_MILLIS = "build_time_millis";
  @SerializedName(SERIALIZED_NAME_BUILD_TIME_MILLIS)
  @javax.annotation.Nullable
  private Integer buildTimeMillis;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private Status status;

  public PreviousBuild() {
  }

  public PreviousBuild buildNum(@javax.annotation.Nullable Integer buildNum) {
    this.buildNum = buildNum;
    return this;
  }

  /**
   * Get buildNum
   * @return buildNum
   */
  @javax.annotation.Nullable
  public Integer getBuildNum() {
    return buildNum;
  }

  public void setBuildNum(@javax.annotation.Nullable Integer buildNum) {
    this.buildNum = buildNum;
  }


  public PreviousBuild buildTimeMillis(@javax.annotation.Nullable Integer buildTimeMillis) {
    this.buildTimeMillis = buildTimeMillis;
    return this;
  }

  /**
   * Get buildTimeMillis
   * @return buildTimeMillis
   */
  @javax.annotation.Nullable
  public Integer getBuildTimeMillis() {
    return buildTimeMillis;
  }

  public void setBuildTimeMillis(@javax.annotation.Nullable Integer buildTimeMillis) {
    this.buildTimeMillis = buildTimeMillis;
  }


  public PreviousBuild status(@javax.annotation.Nullable Status status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public Status getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable Status status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreviousBuild previousBuild = (PreviousBuild) o;
    return Objects.equals(this.buildNum, previousBuild.buildNum) &&
        Objects.equals(this.buildTimeMillis, previousBuild.buildTimeMillis) &&
        Objects.equals(this.status, previousBuild.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buildNum, buildTimeMillis, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreviousBuild {\n");
    sb.append("    buildNum: ").append(toIndentedString(buildNum)).append("\n");
    sb.append("    buildTimeMillis: ").append(toIndentedString(buildTimeMillis)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("build_num", "build_time_millis", "status"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PreviousBuild
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PreviousBuild.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PreviousBuild is not found in the empty JSON string", PreviousBuild.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PreviousBuild.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PreviousBuild` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        Status.validateJsonElement(jsonObj.get("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PreviousBuild.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PreviousBuild' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PreviousBuild> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PreviousBuild.class));

       return (TypeAdapter<T>) new TypeAdapter<PreviousBuild>() {
           @Override
           public void write(JsonWriter out, PreviousBuild value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PreviousBuild read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PreviousBuild given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PreviousBuild
   * @throws IOException if the JSON string is invalid with respect to PreviousBuild
   */
  public static PreviousBuild fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PreviousBuild.class);
  }

  /**
   * Convert an instance of PreviousBuild to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

