/*
 * CircleCI REST API
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Scope
 */
@JsonAdapter(Scope.Adapter.class)
public enum Scope {
  
  WRITE_SETTINGS("write-settings"),
  
  VIEW_BUILDS("view-builds"),
  
  READ_SETTINGS("read-settings"),
  
  TRIGGER_BUILDS("trigger-builds"),
  
  ALL("all"),
  
  STATUS("status"),
  
  NONE("none");

  private String value;

  Scope(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Scope fromValue(String value) {
    for (Scope b : Scope.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Scope> {
    @Override
    public void write(final JsonWriter jsonWriter, final Scope enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Scope read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Scope.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Scope.fromValue(value);
  }
}

